### PR TITLE
Don't leak CFunctionInfo and CTypeInfo

### PR DESCRIPTION
**Pull request by littledivy**
Fixes https://github.com/denoland/deno_core/issues/649
Fixes https://github.com/denoland/deno_core/issues/806

### CODE REVIEW

**Review by bartlomieju — APPROVED** [review]
LGTM!

**Comment by svix-jplatte** [comment]
Note that this was done before and reverted, there is an re-apply PR for this at #714, but AFAIU it's blocked on https://github.com/denoland/deno/pull/24169 passing CI.

**Comment by nathanwhit** [comment]
It looks like this PR is passing CI in deno, but the diff looks essentially identical (the only difference being putting that args and ret into a tuple instead of separate fields).

Why does this work while the original PR failed?

**Comment by littledivy** [comment]
I've been trying to figure that out but its likely that the failures were caused by something unrelated back then. This one is  passing so i'll added the original author as co-author and merge.

**Comment by spolu** [comment]
Thanks!

**Pull request merged**
