### PR TITLE
fix: use call sites when checking for empty frames

### PR DESCRIPTION
**Pull request by nayeemrmn**
Will fix ... https://github.com/denoland/deno/issues/20034.

As we know, `msg.get_stack_frames()` does not get populated properly for async op errors. That's why we use the 'call sites' passed to `prepareStackTrace()` as a source of truth instead. I had forgotten to account for that in one odd place.

### CODE REVIEW

**Comment by bartlomieju** [comment]
@nayeemrmn could you check if this change will help with https://github.com/denoland/deno/issues/18946?

**Comment by nayeemrmn** [comment]
> could you check if this change will help with [denoland/deno#18946](https://github.com/denoland/deno/issues/18946)?

It doesn't, this only has to do with cases where the original error stack is replaced with the location of a dynamic import it passed through because it was wrongly detected as empty.

**Comment by bartlomieju** [comment]
Any chance we could get a regression test for this?

**Review by bartlomieju — APPROVED** [review]
LGTM, thanks for a quick fix!

**Pull request merged**
