### PR TITLE
refactor: use v8::OneByteConst

### PR DESCRIPTION
**Pull request by bartlomieju**
Closes https://github.com/denoland/deno_core/issues/527

Not sure I'm happy with having `v8_static_strings::new_from_static_str`. Maybe all op declarations
should provide their names as `v8::OneByteConst`. Also `v8_static_strings` should be renamed to
`v8_const_strings`?

### CODE REVIEW

**Review by mmastrac — APPROVED** [review]
LGTM

**Comment by mmastrac** [comment]
> Maybe all op declarations should provide their names as v8::OneByteConst

I think that's a good idea. It's a const function, so it's effectively free for us to just generate `name_v8` next to `name`.

**Comment by bartlomieju** [comment]
> > Maybe all op declarations should provide their names as v8::OneByteConst
> 
> I think that's a good idea. It's a const function, so it's effectively free for us to just generate `name_v8` next to `name`.

Argh.... upon further inspection it seems to be impossible right now as `v8::OneByteConst` doesn't implement `Clone` nor `Copy`. Maybe it's something that could be implemented in `rusty_v8`?

**Comment by mmastrac** [comment]
> Not sure I'm happy with having v8_static_strings::new_from_static_str

Actually, we can probably just add a `deref` to `&'static str` for `&'static OneByteConst`, which would allow us to store `&'static OneByteConst` on ops and ExtensionFileSource...

**Comment by mmastrac** [comment]
Looks like 

> Argh.... upon further inspection it seems to be impossible right now as `v8::OneByteConst` doesn't implement `Clone` nor `Copy`. Maybe it's something that could be implemented in `rusty_v8`?

That should be OK for now as `&'static OneByteConst` is `Copy + Clone`.

**Comment by bartlomieju** [comment]
We'll do the necessary changes in a follow up PR.

**Pull request merged**
