### PR TITLE
Adds `clear_modules` to JsRealm and JsRuntime to allow the unloading of modules.

### PR DESCRIPTION
**Pull request by rscarson**
Added `clear_modules` to JsRealm and JsRuntime to allow the unloading of modules.

This change does not affect loaded extensions.

The use case is a very quick reset for an active runtime that does not require reconstructing the runtime, or reloading extensions/ops

The code below was used to check for memory not being cleared from v8 resources:
- Performs 1000 iterations of
    - Load 1000 modules, each storing 1024bytes of data.
    - Clear the modules
```rust
#[cfg(test)]
mod test_module_unload {
  fn get_numbered_module(
    i: usize,
  ) -> (crate::url::Url, Option<crate::FastString>) {
    let name = crate::resolve_path(
      &format!("module{i}.js"),
      &std::env::current_dir()
        .expect("Unable to get current working directory"),
    )
    .expect("Unable to get module url");

    let code = Some(crate::FastString::from(
      "
      let value = `
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla mollis facilisis ex a pretium. Pellentesque pharetra mollis ipsum, laoreet dapibus turpis. Ut volutpat hendrerit justo ac hendrerit. Vivamus id ligula nisl. Proin pretium tincidunt hendrerit. Vivamus ultrices magna neque, id elementum nisl luctus id. Sed finibus, arcu vitae porta ornare, felis nibh convallis neque, eu auctor risus diam ut neque. Sed euismod nisl ut nibh tincidunt interdum. Mauris aliquet mauris odio, vitae eleifend ante imperdiet at. Phasellus dictum sodales mi sit amet fringilla. Aliquam erat volutpat. Ut eget neque eu lorem aliquet molestie. In a purus sit amet velit dapibus semper a ac quam. Ut hendrerit aliquam tempus. Maecenas justo ipsum, venenatis id ipsum nec, euismod rutrum ante. Sed et urna porta dolor dictum pulvinar ut eu enim.
      Vestibulum justo nisl, lacinia consequat quam ut, tristique dapibus arcu. Mauris rhoncus, lectus nec mattis pharetra, lectus neque placerat dolor, vel commodo nunc ligula sit amet justo. Nunc mi.
      `;
      ".to_string(),
    ));

    (name, code)
  }

  #[test]
  fn test_unload() {
    let mut js_runtime = crate::JsRuntime::new(Default::default());

    for iteration in 0..1000 {
      let runtime = &mut js_runtime;
      let future = async move {
        for i in 0..1000 {
          let (name, code) = get_numbered_module(i);
          let mod_id = runtime.load_side_module(&name, code).await?;
          let result = runtime.mod_evaluate(mod_id);
          runtime.run_event_loop(false).await?;
          result.await??;
        }

        Ok::<(), anyhow::Error>(())
      };

      tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .unwrap()
        .block_on(future)
        .expect("Could not run tokio");

      js_runtime.clear_modules();

      if iteration % 100 == 0 {
        println!("Finished {} / 1000 iterations...", iteration);
      }
    }
  }
}
```

### CODE REVIEW

**Comment by bartlomieju** [comment]
Thanks for the PR, could you give some context what is the use case?

**Comment by rscarson** [comment]
> Thanks for the PR, could you give some context what is the use case?

A runtime instance that will need to run a series of unrelated modules over and over, with very tight performance constraints.

Creating a new runtime takes ~20ms, snapshots take about 5ms (and have several constraints that make implementation very difficult in my case).

Unloading the modules (and restoring the state of globalThis from a backup on the JS side) takes only ~1ms and allows me to re-use the runtime and it's extensions

**Comment by bartlomieju** [comment]
> > Thanks for the PR, could you give some context what is the use case?
> 
> A runtime instance that will need to run a series of unrelated modules over and over, with very tight performance constraints, and without side-effects between runs.
> 
> Creating a new runtime takes ~20ms, snapshots take about 5ms (and have several constraints that make implementation very difficult in my case).
> 
> Unloading the modules (and restoring the state of globalThis from a backup on the JS side) takes only ~1ms and allows me to re-use the runtime and it's extensions

Thanks for explanation; I don't have objections to landing the PR, just keep in mind that clearing the loaded modules will likely not clear the whole environment completely - while it might be fine for testing I wouldn't recommended running it in production.

**Review by bartlomieju — CHANGES_REQUESTED** [review]
Please update one of the tests in `core/runtime/modules/tests.rs` that exercises this new API and asserts that the module map is empty.

**Comment by rscarson** [comment]
> > > Thanks for the PR, could you give some context what is the use case?
> > 
> > 
> > A runtime instance that will need to run a series of unrelated modules over and over, with very tight performance constraints, and without side-effects between runs.
> > Creating a new runtime takes ~20ms, snapshots take about 5ms (and have several constraints that make implementation very difficult in my case).
> > Unloading the modules (and restoring the state of globalThis from a backup on the JS side) takes only ~1ms and allows me to re-use the runtime and it's extensions
> 
> Thanks for explanation; I don't have objections to landing the PR, just keep in mind that clearing the loaded modules will likely not clear the whole environment completely - while it might be fine for testing I wouldn't recommended running it in production.

I'll update the function docs accordingly. Would you guys be opposed to another PR in the future that clears the memory a bit better?

**Comment by bartlomieju** [comment]
> I'll update the function docs accordingly. Would you guys be open to another PR in the future that clears the memory a bit better?

Sure, do you have something specific in mind?

**Review by bartlomieju — APPROVED** [review]
Thanks!

**Pull request merged**
